version: "3.3"
services:
  yocto-test:
    image: yocto-test
    user: dev
    privileged: true
    container_name: yocto-test
    network_mode: host
    build:
      context: .
    tty: true
    volumes:
      - ./build:/home/dev/yocto-test/build:rw